import { Response } from "express";
import { prisma } from "../config/database.js";
import { AuthenticatedRequest } from "../middlewares/auth.middleware.js";

export class CompanyController {
  // Admin-only weekly company-mood diagnostic (generated by the n8n flow
  // "PKGD - Diagnóstico Semanal de Empresa", persisted in company_diagnostics).
  // The UI further gates the pre-screen to the "Dirección General" department.
  static async getDiagnostic(_req: AuthenticatedRequest, res: Response) {
    try {
      const latest = await prisma.companyDiagnostic.findFirst({
        orderBy: { created_at: "desc" },
      });

      if (!latest) {
        return res.status(200).json({ has_data: false });
      }

      return res.status(200).json({
        has_data: true,
        summary: latest.summary,
        mood_label: latest.mood_label,
        mood_score: latest.mood_score,
        payload: latest.payload ?? {},
        period_start: latest.period_start,
        period_end: latest.period_end,
        generated_at: latest.created_at,
      });
    } catch (error) {
      console.error("Get company diagnostic error:", error);
      return res.status(500).json({ message: "Failed to fetch company diagnostic" });
    }
  }
}
